# FOS user config
fos_user:
  db_driver:      orm # other valid values are 'mongodb', 'couchdb' and 'propel'
  firewall_name:  main
  user_class:     App\Entity\User
  from_email:
    address: "versendaal@redkiwi.nl"
    sender_name: "Ronan Versendaal"
  registration:
    #        form:
    #            type: AppBundle\Form\UserRegisterType
    confirmation:
      enabled: true
      template:   FOSUserBundle:Registration:email.txt.twig
      from_email:
        address: "versendaal@redkiwi.nl"
        sender_name: "Ronan Versendaal"
  service:
    mailer: fos_user.mailer.twig_swift
  resetting:
    email:
      template:   FOSUserBundle:Resetting:email.txt.twig